DROP TABLE IF EXISTS tournaments_referee CASCADE;
DROP TABLE IF EXISTS scores CASCADE;
DROP TABLE IF EXISTS rating_history CASCADE;
DROP TABLE IF EXISTS pairing CASCADE;
DROP TABLE IF EXISTS matches CASCADE;
DROP TABLE IF EXISTS team_players CASCADE;
DROP TABLE IF EXISTS team CASCADE;
DROP TABLE IF EXISTS ratings CASCADE;
DROP TABLE IF EXISTS courts CASCADE;
DROP TABLE IF EXISTS registrations CASCADE;
DROP TABLE IF EXISTS transactions CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS match_format CASCADE;
DROP TABLE IF EXISTS venue CASCADE;
DROP TABLE IF EXISTS players CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS match_participants CASCADE;


DROP TYPE IF EXISTS match_format CASCADE;
DROP TYPE IF EXISTS tournaments CASCADE;
DROP TYPE IF EXISTS venue CASCADE;
DROP TYPE IF EXISTS players CASCADE;
DROP TYPE IF EXISTS transactions CASCADE;
DROP TYPE IF EXISTS registrations CASCADE;
DROP TYPE IF EXISTS courts CASCADE;
DROP TYPE IF EXISTS ratings CASCADE;
DROP TYPE IF EXISTS team CASCADE;
DROP TYPE IF EXISTS team_players CASCADE;
DROP TYPE IF EXISTS matches CASCADE;
DROP TYPE IF EXISTS pairing CASCADE;
DROP TYPE IF EXISTS rating_history CASCADE;
DROP TYPE IF EXISTS scores CASCADE;
DROP TYPE IF EXISTS tournaments_referee CASCADE;



